apiVersion: v2
name: openbao
description: A OpenBao helmetica service

# Transmuter charts are always application charts
type: application

version: 0.2.3

appVersion: "0.28.5"

dependencies:
  - name: openbao
    version: 0.28.5
    repository: oci://ghcr.io/openbao/charts
